### ISSUE TITLE
CSRF on multiple places like settings

### ISSUE THREAD

**Issue by HitmanAlharbi** [echoCTF/echoCTF.RED#393]
Hey echoCTF team,

I found CSRF on multiple places like /settings 

PoC:
```js
$.ajax({
  type: "POST",
  url: "http://localhost:8082/profile/settings",
  data: "_csrf-red=iAI21BQ7sS_cutqWW9WZglu5QVZ_i0Cw5K2VwAQONm3Zb2zkQ2jlQbL3ltoOnuOvH-NyIDfxOuWA7viYXjdQVQ%3d%3d&SettingsForm%5bemail%5d=PWNED@gmail.com&SettingsForm%5bnew_password%5d=&SettingsForm%5bconfirm_password%5d=",
  processData: false,
  success: function(msg) {
    alert("Done");
  }
});
```

**Comment by proditis** [comment]
Ok so after a bit of investigation here are the findings:

The csrfValidation() function checks if either of these is valid:
```php
        return $this->validateCsrfTokenInternal($this->getBodyParam($this->csrfParam), $trueToken)
            || $this->validateCsrfTokenInternal($this->getCsrfTokenFromHeader(), $trueToken);
```

This header validation is part of the cookie validation process for the CSRF token.

The csrf token you included on your `$.ajax` request is not validated because you already include another token on your headers (check the request and you'll see X-CSRF-TOKEN being set). 

The case where this would have been dangerous is if we have an XSS on our site or embeded content which we dont. CORS makes it at least somewhat difficult to post from another site.


However, i still consider this an issue so i'll include a fix for this for the forms that interest us

**Comment by proditis** [comment]
The current fix is applied on 
* profile/settings
* claim
* spin
* challenge/view

In theory this "bug" will be available on all post operations. But i think these are the ones that interest us. Let me know if you think i've missed any endpoints
