### ISSUE TITLE
'echoctfred_db' container problem - database can not start

### ISSUE THREAD

**Issue by Infouzi** [echoCTF/echoCTF.RED#460]
I have been struggling to try and make the initial setting for the "echoctfred stack" with Docker. Every container is running fine, except the "database container": echoctfred_db.
When i go to the logs, this is what i see.
"mariadbd: Please consult the Knowledge Base to find out how to run mysqld as root!"

<img width="1134" alt="echoctfred_db-container-problem" src="https://user-images.githubusercontent.com/61884413/144032347-d43bdeac-780e-4c42-bd48-f50f6fcf01c9.png">

From what i understood, "mysqld" is trying to run as "**root**", which is prohibited and mariadb doesn't allow that directly, so, it causes the problem.
The thing is, i tried to change the user in the contrib/Dockerfile-mariadb to "mysql", but it didn't even build (user permission problems).

Did anyone encountered this before, it really does frustrate me, thanks.

**Comment by proditis** [comment]
Hi there @Infouzi 

Yes something seems to be wrong indeed. This is not something you did, something changed that caused this. 
I was just about to investigate this as well, I just got notified from our CI about this failure. 

I will investigate and let you know.

**Comment by Infouzi** [comment]
Thanks. I appreciate the feedback.
Let me know in case anything new has changed. In the meanwhile, i will still try any appropriate solutions that comes to me.

Good luck

**Comment by proditis** [comment]
Hi there, 

This took a bit longer than I expected, but I think the culprits were found. 

Adding here for future reference. 

The issue was that latest versions of mariadb docker images, use a different start up command. We use the official images as source for our db container. Our `docker-entrypoint.sh` was not updated for the new command and it caused it to fail to switch to a non privileged user.  As such we got the errors for running as root.

Another issue that was *accidentally* identified, was the fact that `docker-compose pull` command doesn't pull anything!!! As a temporary solution the quick start instructions were updated, but the reason for this is still a mystery to me...

Can you please try the following and report back on success or failure?  
* Remove docker data related to the applications `docker-compose down --rmi all -v --remove-orphans`
* Update your local repo with `git pull`
* Fetch the images manually (since i have no idea why `docker-compose` refuses to do so).
  ```
  docker pull echothrust/echoctf.red-db:latest
  docker pull echothrust/echoctf.red-backend:latest
  docker pull echothrust/echoctf.red-frontend:latest
  docker pull echothrust/echoctf.red-vpn:latest
  ```
* and give `docker-compose up` another try.

**Comment by Infouzi** [comment]
Hi @proditis ,

Sorry for the late reply.

Indeed, during my debugging for the problem, i reached a point where i started to look in the official mariadb docker image dockerfile, and started to analyze the `entrypoint.sh` file. However, it was a little too much for me to debug it all in this moment. 

So, **thank you very** much for the effort put into this.

It is working like a charm now. <3
