### ISSUE TITLE
[BUG] Host Header Injection when using docker images

### ISSUE THREAD

**Issue by xcodeOn1** [echoCTF/echoCTF.RED#955]
**Describe the bug**

"Host Header Injection"  i can inject host in by Get any website i want .

**To Reproduce**
1. go to backend login [http://172.26.0.2/index.php?r=site%2Flogin]
2. send this url request to burp and change http method from POST to GET : [http://172.26.0.2/index.php?r=site%2Flogin]
3. change it like this one and request will redirect to twitter in our example :

```sh
GET https://twitter.com/ HTTP/1.1
Host: 172.26.0.2
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: http://172.26.0.2
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.134 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Referer: http://172.26.0.2
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: PHPSESSID=qhicva96jma0bcph7upmdaeka3
Connection: close
```

Poc :

 ![Script](https://gcdnb.pbrd.co/images/iZGHHyo69lEn.png?o=1)

**Comment by proditis** [comment]
Hi there and THANK YOU for reporting this :heart: 

This is part of the intended behavior for the docker images.
For production environments the best option is to use the provided playbooks (under `ansible/runonce`) to setup the systems, as these ensure (among other things) that the hostname is enforced. (see https://github.com/echoCTF/echoCTF.RED/blob/890abb0d58c01584a0d3ce25d0e9c8e6d0188163/ansible/templates/nginx.conf.j2#L346 and https://github.com/echoCTF/echoCTF.RED/blob/890abb0d58c01584a0d3ce25d0e9c8e6d0188163/frontend/config/web.php#L147 )

However, I leave this issue open in order to ensure that this is mentioned somewhere in the documentation and will update accordingly.
